object Version {
    const val coreKtxVersion = "1.8.0"
    const val appCompatVersion = "1.7.0"
    const val materialVersion = "1.5.0"
    const val constraintLayoutVersion = "2.1.4"
    const val swipeRefreshLayoutVersion = "1.1.0"
    const val activityKtxVersion = "1.6.1"
    const val lifecycleVersion = "2.4.1"
    const val retrofitVersion = "2.9.0"
    const val okHttpInterceptorVersion = "4.9.0"
    const val glideVersion = "4.11.0"
    const val circleImageViewVersion = "3.1.0"
    const val roomVersion = "2.4.2"
    const val mockitoVersion = "4.0.0"
    const val coroutinesTestVersion = "1.5.2"
    const val coreTestingVersion = "2.1.0"
    const val robolectricVersion = "4.10.3"
    const val androidxTestCoreVersion = "1.6.1"
    const val junitVersion = "4.13.2"
    const val espressoVersion = "3.6.1"
    const val testRunnerVersion = "1.5.2"
    const val testRulesVersion = "1.5.0"
    const val junitKtxVersion = "1.2.1"
    const val extJunitVersion = "1.1.5"
    const val hiltVersion = "2.44"
}